import { Layout } from "@/components/layout/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  TrendingDown, 
  Sparkles,
  Target,
  CheckCircle2,
  Brain,
  Download,
  FileText
} from "lucide-react";
import { mockRecommendations } from "@/lib/mockData";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import type { AIRecommendation } from "@/types/lca";
import { InsightCard } from "@/components/insights/InsightCard";
import { InsightDetailsDialog } from "@/components/insights/InsightDetailsDialog";

const Insights = () => {
  const { toast } = useToast();
  const [recommendations, setRecommendations] = useState(mockRecommendations);
  const [selectedInsight, setSelectedInsight] = useState<AIRecommendation | null>(null);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [acceptedCount, setAcceptedCount] = useState(12);

  const highPriority = recommendations.filter(r => r.priority === 'high');
  const totalReduction = recommendations.reduce((sum, r) => sum + r.potentialImpactReduction, 0);

  const handleAccept = (id: string) => {
    setRecommendations(recommendations.filter(r => r.id !== id));
    setAcceptedCount(prev => prev + 1);
    setDetailsOpen(false);
    toast({
      title: "Recommendation Accepted",
      description: "This insight has been added to your implementation queue.",
    });
  };

  const handleDismiss = (id: string) => {
    setRecommendations(recommendations.filter(r => r.id !== id));
    setDetailsOpen(false);
    toast({
      title: "Recommendation Dismissed",
      description: "This insight has been removed from your list.",
    });
  };

  const handleDetails = (recommendation: AIRecommendation) => {
    setSelectedInsight(recommendation);
    setDetailsOpen(true);
  };

  const generateReportContent = (recommendation: AIRecommendation) => {
    return `
================================================================================
                        TERRALENS LCA - INSIGHT REPORT
================================================================================

RECOMMENDATION: ${recommendation.title}
TYPE: ${recommendation.type.replace(/-/g, ' ').toUpperCase()}
PRIORITY: ${recommendation.priority.toUpperCase()}
GENERATED: ${new Date().toISOString()}

--------------------------------------------------------------------------------
DESCRIPTION
--------------------------------------------------------------------------------
${recommendation.description}

--------------------------------------------------------------------------------
KEY METRICS
--------------------------------------------------------------------------------
Potential Impact Reduction: ${recommendation.potentialImpactReduction}%
Implementation Cost: ${recommendation.implementationCost}
Implementation Timeline: ${recommendation.implementationTime}
AI Confidence Score: ${recommendation.confidence}%

--------------------------------------------------------------------------------
IMPLEMENTATION STEPS
--------------------------------------------------------------------------------
1. Review current operational parameters and identify optimization opportunities
2. Conduct feasibility study with engineering team
3. Develop phased implementation plan
4. Allocate resources and set milestones
5. Execute implementation with continuous monitoring
6. Measure and document impact reduction metrics
7. Iterate and optimize based on results

--------------------------------------------------------------------------------
EXPECTED OUTCOMES
--------------------------------------------------------------------------------
• Reduced carbon footprint by ${recommendation.potentialImpactReduction}%
• Improved operational efficiency
• Enhanced sustainability compliance
• Long-term cost savings
• Improved Material Circularity Index (MCI)

--------------------------------------------------------------------------------
RISK ASSESSMENT
--------------------------------------------------------------------------------
Implementation Risk: ${recommendation.implementationCost === 'high' ? 'High' : recommendation.implementationCost === 'medium' ? 'Medium' : 'Low'}
Timeline Risk: ${recommendation.implementationTime === 'long' ? 'High' : recommendation.implementationTime === 'medium' ? 'Medium' : 'Low'}
ROI Confidence: ${recommendation.confidence}%

================================================================================
                     Generated by TerraLens AI Engine
================================================================================
    `.trim();
  };

  const generateAIAnalysisContent = (recommendation: AIRecommendation) => {
    return `
================================================================================
                    TERRALENS AI - DEEP ANALYSIS REPORT
================================================================================

RECOMMENDATION: ${recommendation.title}
ANALYSIS TYPE: Machine Learning Environmental Impact Assessment
MODEL VERSION: TerraLens AI v2.0
GENERATED: ${new Date().toISOString()}

--------------------------------------------------------------------------------
AI MODEL SUMMARY
--------------------------------------------------------------------------------
This analysis was generated using TerraLens's proprietary machine learning 
models trained on extensive metallurgical and mining industry data. The 
recommendation is based on pattern recognition across similar operations 
and environmental impact correlations.

Confidence Level: ${recommendation.confidence}%
Data Points Analyzed: ${Math.floor(Math.random() * 50000) + 10000}
Historical Comparisons: ${Math.floor(Math.random() * 500) + 100} similar operations
Industry Benchmark Alignment: ${Math.floor(Math.random() * 20) + 80}%

--------------------------------------------------------------------------------
ENVIRONMENTAL IMPACT ANALYSIS
--------------------------------------------------------------------------------

Carbon Footprint Reduction Potential:
- Direct Emissions (Scope 1): ${Math.floor(recommendation.potentialImpactReduction * 0.4)}% reduction
- Indirect Emissions (Scope 2): ${Math.floor(recommendation.potentialImpactReduction * 0.35)}% reduction
- Value Chain (Scope 3): ${Math.floor(recommendation.potentialImpactReduction * 0.25)}% reduction

Resource Efficiency Improvements:
- Energy Consumption: -${Math.floor(Math.random() * 15) + 5}%
- Water Usage: -${Math.floor(Math.random() * 12) + 3}%
- Raw Material Waste: -${Math.floor(Math.random() * 20) + 8}%

Circularity Index Impact:
- Current MCI: ${(Math.random() * 0.3 + 0.4).toFixed(2)}
- Projected MCI: ${(Math.random() * 0.2 + 0.6).toFixed(2)}
- Improvement: +${Math.floor(Math.random() * 15) + 10}%

--------------------------------------------------------------------------------
LIFE CYCLE ASSESSMENT BREAKDOWN
--------------------------------------------------------------------------------

Phase Impact Analysis:
1. Raw Material Extraction: ${Math.floor(Math.random() * 30) + 20}% of total impact
2. Processing & Manufacturing: ${Math.floor(Math.random() * 25) + 30}% of total impact
3. Transportation & Distribution: ${Math.floor(Math.random() * 15) + 10}% of total impact
4. Use Phase: ${Math.floor(Math.random() * 10) + 5}% of total impact
5. End-of-Life Management: ${Math.floor(Math.random() * 15) + 5}% of total impact

Optimization Focus Areas:
• ${recommendation.type === 'process-optimization' ? 'Primary focus on manufacturing process improvements' : ''}
• ${recommendation.type === 'material-substitution' ? 'Primary focus on alternative material sourcing' : ''}
• ${recommendation.type === 'energy-efficiency' ? 'Primary focus on energy consumption patterns' : ''}
• ${recommendation.type === 'waste-reduction' ? 'Primary focus on waste stream management' : ''}
• ${recommendation.type === 'circularity' ? 'Primary focus on closed-loop material flows' : ''}

--------------------------------------------------------------------------------
PREDICTIVE MODELING RESULTS
--------------------------------------------------------------------------------

Short-term (3 months):
- Expected impact reduction: ${Math.floor(recommendation.potentialImpactReduction * 0.3)}%
- Confidence interval: ±${Math.floor(Math.random() * 5) + 2}%

Medium-term (6-12 months):
- Expected impact reduction: ${Math.floor(recommendation.potentialImpactReduction * 0.7)}%
- Confidence interval: ±${Math.floor(Math.random() * 8) + 3}%

Long-term (12+ months):
- Expected impact reduction: ${recommendation.potentialImpactReduction}%
- Confidence interval: ±${Math.floor(Math.random() * 10) + 5}%

--------------------------------------------------------------------------------
INDUSTRY BENCHMARKING
--------------------------------------------------------------------------------

Compared to industry peers implementing similar measures:
- Top 10% performers: ${recommendation.potentialImpactReduction + Math.floor(Math.random() * 5) + 3}% reduction
- Industry average: ${recommendation.potentialImpactReduction - Math.floor(Math.random() * 8) - 5}% reduction
- Your projected performance: ${recommendation.potentialImpactReduction}% reduction

Competitive positioning: ${recommendation.potentialImpactReduction > 15 ? 'Above average' : 'Average'}

--------------------------------------------------------------------------------
RECOMMENDATIONS FOR IMPLEMENTATION
--------------------------------------------------------------------------------

Technical Requirements:
• Infrastructure upgrades: ${recommendation.implementationCost === 'high' ? 'Significant' : recommendation.implementationCost === 'medium' ? 'Moderate' : 'Minimal'}
• Personnel training: Required for ${Math.floor(Math.random() * 50) + 20} staff members
• Monitoring systems: ${recommendation.implementationCost === 'low' ? 'Existing systems adequate' : 'Upgrades recommended'}

Resource Allocation:
• Estimated investment: $${Math.floor(Math.random() * 500) + 100}K - $${Math.floor(Math.random() * 2000) + 500}K
• Personnel hours: ${Math.floor(Math.random() * 2000) + 500} hours
• External consultancy: ${recommendation.implementationCost === 'high' ? 'Recommended' : 'Optional'}

================================================================================
                     Generated by TerraLens AI Engine
                    Model: Environmental Impact Predictor v2.0
                    Data sources: ISO 14044, ecoinvent 3.8, GaBi
================================================================================
    `.trim();
  };

  const handleDownloadReport = (recommendation: AIRecommendation) => {
    const content = generateReportContent(recommendation);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TerraLens-Report-${recommendation.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Report Downloaded",
      description: `Report for "${recommendation.title}" has been downloaded.`,
    });
  };

  const handleDownloadAIAnalysis = (recommendation: AIRecommendation) => {
    const content = generateAIAnalysisContent(recommendation);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TerraLens-AI-Analysis-${recommendation.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "AI Analysis Downloaded",
      description: `AI analysis for "${recommendation.title}" has been downloaded.`,
    });
  };

  const handleDownloadAllReports = () => {
    recommendations.forEach((rec, index) => {
      setTimeout(() => handleDownloadReport(rec), index * 500);
    });
  };

  const filterByType = (type: string) => {
    if (type === 'all') return recommendations;
    if (type === 'process') return recommendations.filter(r => r.type === 'process-optimization');
    if (type === 'materials') return recommendations.filter(r => r.type === 'material-substitution');
    if (type === 'energy') return recommendations.filter(r => r.type === 'energy-efficiency');
    if (type === 'circularity') return recommendations.filter(r => r.type === 'circularity' || r.type === 'waste-reduction');
    return recommendations;
  };

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-primary" />
              <h1 className="text-3xl font-bold tracking-tight">AI Insights</h1>
            </div>
            <p className="text-muted-foreground">
              Machine learning-powered recommendations for sustainability improvement
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={handleDownloadAllReports}>
              <Download className="h-4 w-4 mr-2" />
              Export All Reports
            </Button>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid gap-4 sm:grid-cols-4">
          <Card className="bg-gradient-to-br from-primary/10 to-primary/5">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="h-4 w-4 text-primary" />
                <p className="text-sm font-medium">Active Insights</p>
              </div>
              <p className="text-3xl font-bold">{recommendations.length}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-2">
                <Target className="h-4 w-4 text-destructive" />
                <p className="text-sm font-medium">High Priority</p>
              </div>
              <p className="text-3xl font-bold">{highPriority.length}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-2">
                <TrendingDown className="h-4 w-4 text-emerald-600" />
                <p className="text-sm font-medium">Potential Savings</p>
              </div>
              <p className="text-3xl font-bold">{totalReduction}%</p>
              <p className="text-xs text-muted-foreground">combined impact reduction</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                <p className="text-sm font-medium">Implemented</p>
              </div>
              <p className="text-3xl font-bold">{acceptedCount}</p>
              <p className="text-xs text-muted-foreground">this quarter</p>
            </CardContent>
          </Card>
        </div>

        {/* Recommendations */}
        <Tabs defaultValue="all" className="space-y-4">
          <TabsList>
            <TabsTrigger value="all">All Insights</TabsTrigger>
            <TabsTrigger value="process">Process</TabsTrigger>
            <TabsTrigger value="materials">Materials</TabsTrigger>
            <TabsTrigger value="energy">Energy</TabsTrigger>
            <TabsTrigger value="circularity">Circularity</TabsTrigger>
          </TabsList>

          {['all', 'process', 'materials', 'energy', 'circularity'].map((tab) => (
            <TabsContent key={tab} value={tab} className="space-y-4">
              {filterByType(tab).length === 0 ? (
                <Card>
                  <CardContent className="p-12 text-center">
                    <CheckCircle2 className="h-12 w-12 mx-auto text-emerald-500 mb-4" />
                    <h3 className="text-lg font-medium mb-2">All caught up!</h3>
                    <p className="text-muted-foreground">
                      No pending recommendations in this category.
                    </p>
                  </CardContent>
                </Card>
              ) : (
                <div className="grid gap-4 md:grid-cols-2">
                  {filterByType(tab).map((rec) => (
                    <InsightCard 
                      key={rec.id} 
                      recommendation={rec}
                      onAccept={handleAccept}
                      onDismiss={handleDismiss}
                      onDetails={handleDetails}
                    />
                  ))}
                </div>
              )}
            </TabsContent>
          ))}
        </Tabs>

        {/* Details Dialog */}
        <InsightDetailsDialog
          recommendation={selectedInsight}
          open={detailsOpen}
          onOpenChange={setDetailsOpen}
          onAccept={handleAccept}
          onDismiss={handleDismiss}
          onDownloadReport={handleDownloadReport}
          onDownloadAIAnalysis={handleDownloadAIAnalysis}
        />
      </div>
    </Layout>
  );
};

export default Insights;
